import type { LessonSeed } from "../lessons";

export const week8LessonSeeds: LessonSeed[] = [
  {
    title: "struct で関連する値をまとめる",
    goal: "複数の値をひとつの型としてまとめ、メンバー名で読み取る。",
    minutes: 35,
    explanation: "struct は複数のメンバーを持つ新しい型を定義します。Point のような型を作ると、x と y が同じ座標を表すことをコード上でも示せます。メンバーはオブジェクト名の後に . を付けて読み書きします。",
    example: "#include <iostream>\n\nstruct Point {\n    int x;\n    int y;\n};\n\nint main() {\n    const Point spawn{3, 4};\n    std::cout << spawn.x << ' ' << spawn.y << '\\n';\n}",
    exampleOutput: "3 4",
    commonMistake: "メンバーの順序を間違えて初期化したり、座標を別々の変数のまま扱ったりする。",
    quiz: {
      question: "Point position の x メンバーを読む式は？",
      choices: ["position.x", "position->x", "Point::x"],
      answer: 0,
      explanation: "オブジェクトのメンバーには . を使います。-> はポインタ経由のアクセスです。",
    },
    prompt: "struct Point { int x; int y; }; を定義し、入力された x と y から Point を作って `x: <値> y: <値>` と表示してください。",
    solution: "#include <iostream>\n\nstruct Point { int x; int y; };\n\nint main() {\n    int x{}, y{};\n    std::cin >> x >> y;\n    const Point position{x, y};\n    std::cout << \"x: \" << position.x << \" y: \" << position.y << '\\n';\n    return 0;\n}",
    input: "3 4\n",
    tests: [
      { input: "3 4\n", output: "x: 3 y: 4" },
      { input: "0 0\n", output: "x: 0 y: 0" },
      { input: "-2 7\n", output: "x: -2 y: 7" },
    ],
    hints: [
      "Point 型に int の x と y を宣言します。",
      "Point position{x, y}; の順で入力値をまとめます。",
      "position.x と position.y を指定された形式で出力します。",
    ],
    debug: {
      code: "struct Point { int x; int y; };\nPoint position{3, 4};\nstd::cout << position->x;",
      fix: "std::cout << position.x;",
      explanation: "position はポインタではなく Point オブジェクトなので、メンバーへは . でアクセスします。",
    },
  },
  {
    title: "オブジェクトのメンバーを更新する",
    goal: "struct の各メンバーを通じて、ひとつのオブジェクトの状態を扱う。",
    minutes: 35,
    explanation: "Player のような struct は、名前とHPなど関連する状態を一緒に持てます。初期化子リストはメンバー宣言の順に値を対応させます。変更可能なオブジェクトなら player.hp のように特定のメンバーだけを更新できます。",
    example: "#include <iostream>\n#include <string>\n\nstruct Player { std::string name; int hp; };\n\nint main() {\n    Player player{\"Ada\", 80};\n    player.hp += 10;\n    std::cout << player.name << \": \" << player.hp << '\\n';\n}",
    exampleOutput: "Ada: 90",
    commonMistake: "メンバーの宣言順と異なる順で値を渡したり、const オブジェクトのメンバーを変更しようとしたりする。",
    quiz: {
      question: "struct Player { std::string name; int hp; }; に合わせた初期化は？",
      choices: ["Player p{\"Ada\", 80};", "Player p{80, \"Ada\"};", "Player p{\"Ada\"};"],
      answer: 0,
      explanation: "集成体初期化ではメンバー宣言順に対応する値を渡します。",
    },
    prompt: "Player に std::string name と int hp を持たせます。名前とHPを読み、Player を初期化して `name: <名前>` と `hp: <値>` を2行で表示してください。",
    solution: "#include <iostream>\n#include <string>\n\nstruct Player { std::string name; int hp; };\n\nint main() {\n    Player player;\n    std::cin >> player.name >> player.hp;\n    std::cout << \"name: \" << player.name << '\\n';\n    std::cout << \"hp: \" << player.hp << '\\n';\n    return 0;\n}",
    input: "Ada 80\n",
    tests: [
      { input: "Ada 80\n", output: "name: Ada\nhp: 80" },
      { input: "Player 0\n", output: "name: Player\nhp: 0" },
      { input: "Reito 120\n", output: "name: Reito\nhp: 120" },
    ],
    hints: [
      "Player の name は std::string、hp は int です。",
      "std::cin から name と hp を順に読み取れます。",
      "player.name と player.hp を別々の行に出力します。",
    ],
    debug: {
      code: "struct Player { std::string name; int hp; };\nPlayer player{80, \"Ada\"};",
      fix: "Player player{\"Ada\", 80};",
      explanation: "値はメンバー宣言順に name、hp と並べます。",
    },
  },
  {
    title: "enum class で選択肢を表す",
    goal: "意味のある名前を持つ列挙型で、数値コードを安全な選択肢に変換する。",
    minutes: 35,
    explanation: "enum class は取りうる選択肢を型として表します。整数と暗黙に混ざらないため、入力コードを列挙値へ明示的に対応付ける設計にできます。switch の case には列挙子を指定します。",
    example: "#include <iostream>\n\nenum class Menu { Start, Pause, Unknown };\n\nint main() {\n    const Menu selected{Menu::Pause};\n    switch (selected) {\n    case Menu::Start: std::cout << \"start\\n\"; break;\n    case Menu::Pause: std::cout << \"pause\\n\"; break;\n    case Menu::Unknown: std::cout << \"unknown\\n\"; break;\n    }\n}",
    exampleOutput: "pause",
    commonMistake: "enum class の値を修飾せずに書いたり、入力整数を検証なしで選択肢として使ったりする。",
    quiz: {
      question: "enum class State { Ready }; の値を指定する正しい書き方は？",
      choices: ["State::Ready", "Ready", "State.Ready"],
      answer: 0,
      explanation: "enum class の列挙子は型名で修飾し、State::Ready と書きます。",
    },
    prompt: "入力コード1を Start、2を Pause、それ以外を Unknown に対応させ、enum class と switch を使って `start`、`pause`、`unknown` のいずれかを表示してください。",
    solution: "#include <iostream>\n\nenum class Menu { Start, Pause, Unknown };\n\nint main() {\n    int code{};\n    std::cin >> code;\n    Menu selected{Menu::Unknown};\n    if (code == 1) selected = Menu::Start;\n    else if (code == 2) selected = Menu::Pause;\n    switch (selected) {\n    case Menu::Start: std::cout << \"start\\n\"; break;\n    case Menu::Pause: std::cout << \"pause\\n\"; break;\n    case Menu::Unknown: std::cout << \"unknown\\n\"; break;\n    }\n    return 0;\n}",
    input: "2\n",
    tests: [
      { input: "1\n", output: "start" },
      { input: "2\n", output: "pause" },
      { input: "9\n", output: "unknown" },
    ],
    hints: [
      "Start、Pause、Unknown を Menu の選択肢として定義します。",
      "整数コードを if と else if で列挙値へ変換します。",
      "switch の各 case で対応する小文字の結果を出力します。",
    ],
    debug: {
      code: "enum class Menu { Start, Pause };\nMenu selected{Start};",
      fix: "Menu selected{Menu::Start};",
      explanation: "enum class の値は列挙型の名前で修飾する必要があります。",
    },
  },
  {
    title: "名前空間で関数を整理する",
    goal: "関連する関数を名前空間にまとめ、用途を呼び出し側で明示する。",
    minutes: 35,
    explanation: "namespace は関数や型の名前をグループ化します。別の機能が同じ短い関数名を使っても衝突しにくくなり、呼び出し側でも rules::clampScore のように所属が分かります。",
    example: "#include <iostream>\n\nnamespace rules {\nint clampScore(int score) {\n    if (score < 0) return 0;\n    if (score > 100) return 100;\n    return score;\n}\n}\n\nint main() {\n    std::cout << rules::clampScore(125) << '\\n';\n}",
    exampleOutput: "100",
    commonMistake: "定義した名前空間を呼び出し時に付け忘れたり、using namespace をヘッダーへ広げたりする。",
    quiz: {
      question: "namespace game 内の int score() を呼び出す式は？",
      choices: ["game::score()", "game.score()", "score::game()"],
      answer: 0,
      explanation: "名前空間名と中の名前はスコープ解決演算子 :: でつなぎます。",
    },
    prompt: "namespace rules に int clampScore(int score) を定義し、score を0未満なら0、100超なら100、それ以外ならそのまま返してください。入力値をこの関数に渡して結果を表示します。",
    solution: "#include <iostream>\n\nnamespace rules {\nint clampScore(int score) {\n    if (score < 0) return 0;\n    if (score > 100) return 100;\n    return score;\n}\n}\n\nint main() {\n    int score{};\n    std::cin >> score;\n    std::cout << rules::clampScore(score) << '\\n';\n    return 0;\n}",
    input: "125\n",
    tests: [
      { input: "125\n", output: "100" },
      { input: "75\n", output: "75" },
      { input: "-4\n", output: "0" },
    ],
    hints: [
      "関数を namespace rules の波括弧の内側に定義します。",
      "上限と下限を if で調べてから値を返します。",
      "呼び出し側では rules::clampScore(score) と書きます。",
    ],
    debug: {
      code: "namespace rules { int clampScore(int value) { return value; } }\nstd::cout << rules.clampScore(80);",
      fix: "std::cout << rules::clampScore(80);",
      explanation: "名前空間のスコープ解決にはドットではなく :: を使います。",
    },
  },
  {
    title: "構造体の状態を列挙型で表す",
    goal: "構造体のデータから状態を判定し、enum class の値として返す。",
    minutes: 40,
    explanation: "整数のHPから状態を判定して、bool だけでなく意味の分かる LifeState を返すことができます。関数に const Character& を渡せば、状態を調べるだけでオブジェクトをコピーせず、変更もしない意図を表せます。",
    example: "#include <iostream>\n\nenum class LifeState { Alive, Down };\nstruct Character { int hp; };\n\nLifeState stateOf(const Character& character) {\n    return character.hp > 0 ? LifeState::Alive : LifeState::Down;\n}\n\nint main() {\n    const Character player{50};\n    std::cout << (stateOf(player) == LifeState::Alive ? \"alive\\n\" : \"down\\n\");\n}",
    exampleOutput: "alive",
    commonMistake: "状態を表す値として任意の整数を返し、0や1が何を意味するかを呼び出し側に推測させる。",
    quiz: {
      question: "Character のHPが0以下のとき、stateOf が返す値は？",
      choices: ["LifeState::Alive", "LifeState::Down", "nullptr"],
      answer: 1,
      explanation: "Alive はHPが正のときだけです。0以下なら Down を返します。",
    },
    prompt: "Character に int hp を持たせ、LifeState を返す stateOf(const Character&) を定義してください。入力したHPから状態を判定し、alive または down を表示します。",
    solution: "#include <iostream>\n\nenum class LifeState { Alive, Down };\nstruct Character { int hp; };\n\nLifeState stateOf(const Character& character) {\n    if (character.hp > 0) return LifeState::Alive;\n    return LifeState::Down;\n}\n\nint main() {\n    Character player{};\n    std::cin >> player.hp;\n    const LifeState state{stateOf(player)};\n    if (state == LifeState::Alive) std::cout << \"alive\\n\";\n    else std::cout << \"down\\n\";\n    return 0;\n}",
    input: "50\n",
    tests: [
      { input: "50\n", output: "alive" },
      { input: "1\n", output: "alive" },
      { input: "0\n", output: "down" },
    ],
    hints: [
      "LifeState に Alive と Down を定義します。",
      "stateOf は const Character& を受け取り hp を読みます。",
      "hp が正なら Alive、そうでなければ Down を選んで表示します。",
    ],
    debug: {
      code: "enum class LifeState { Alive, Down };\nif (player.hp > 0) return Alive;",
      fix: "if (player.hp > 0) return LifeState::Alive;",
      explanation: "enum class の列挙子を返すときも型名で修飾します。",
    },
  },
  {
    title: "構造体を受け取り新しい値を返す",
    goal: "小さな構造体を値として受け取り、計算結果の構造体を返す。",
    minutes: 40,
    explanation: "Vector2 のように小さな値をまとめた型は、値渡しして結果を返す設計にできます。moveBy は受け取った position を直接変更せず、新しい座標を返します。呼び出し側は返された値を明示的に受け取ります。",
    example: "#include <iostream>\n\nstruct Vector2 { int x; int y; };\n\nVector2 moveBy(Vector2 position, Vector2 delta) {\n    return {position.x + delta.x, position.y + delta.y};\n}\n\nint main() {\n    const Vector2 result{moveBy({2, 3}, {1, 1})};\n    std::cout << result.x << ' ' << result.y << '\\n';\n}",
    exampleOutput: "3 4",
    commonMistake: "戻り値を無視したり、関数内の仮引数を変更しただけで呼び出し元も変わると思ったりする。",
    quiz: {
      question: "値渡しされた Vector2 position のメンバーを関数内で変えたとき、呼び出し元の position は？",
      choices: ["変更されない", "必ず消える", "呼び出し元と共有される"],
      answer: 0,
      explanation: "値渡しされた position はコピーです。新しい値を返し、呼び出し側が受け取ります。",
    },
    prompt: "Vector2 に x と y を持たせます。moveBy(Vector2 position, Vector2 delta) が各成分を足した新しい Vector2 を返すようにし、入力された現在位置と移動量から結果を表示してください。",
    solution: "#include <iostream>\n\nstruct Vector2 { int x; int y; };\n\nVector2 moveBy(Vector2 position, Vector2 delta) {\n    return {position.x + delta.x, position.y + delta.y};\n}\n\nint main() {\n    Vector2 position{};\n    Vector2 delta{};\n    std::cin >> position.x >> position.y >> delta.x >> delta.y;\n    const Vector2 result{moveBy(position, delta)};\n    std::cout << result.x << ' ' << result.y << '\\n';\n    return 0;\n}",
    input: "2 3 1 1\n",
    tests: [
      { input: "2 3 1 1\n", output: "3 4" },
      { input: "0 0 -2 5\n", output: "-2 5" },
      { input: "10 -4 3 -6\n", output: "13 -10" },
    ],
    hints: [
      "Vector2 の x と y を int で定義します。",
      "moveBy は position と delta の両方を値で受け取ります。",
      "{position.x + delta.x, position.y + delta.y} を返します。",
    ],
    debug: {
      code: "Vector2 moveBy(Vector2 position, Vector2 delta) {\n    position.x += delta.x;\n    position.y += delta.y;\n}\nVector2 result = moveBy(position, delta);",
      fix: "Vector2 moveBy(Vector2 position, Vector2 delta) {\n    return {position.x + delta.x, position.y + delta.y};\n}",
      explanation: "戻り値型が Vector2 なので、関数は計算した新しい Vector2 を return します。",
    },
  },
  {
    title: "週末評価：型を使ったミニ戦闘処理",
    goal: "struct、enum class、namespace と参照渡しを組み合わせて状態更新を表す。",
    minutes: 50,
    explanation: "Enemy はHPという状態を持ち、Weapon は攻撃の種類を表します。battle 名前空間に攻撃処理をまとめると、責務と所属が明確です。attack は Enemy& を通じて対象のHPを更新し、HPが0未満にならないようにします。",
    example: "#include <algorithm>\n\nenum class Weapon { Sword, Magic };\nstruct Enemy { int hp; };\n\nnamespace battle {\nint damageFor(Weapon weapon) { return weapon == Weapon::Sword ? 5 : 12; }\nvoid attack(Enemy& enemy, Weapon weapon) {\n    enemy.hp = std::max(0, enemy.hp - damageFor(weapon));\n}\n}",
    exampleOutput: "HP 30 の敵に Magic を使うと HP 18",
    commonMistake: "Enemy を値渡しにして呼び出し元のHPを更新できなかったり、攻撃後のHPが負数になったりする。",
    quiz: {
      question: "attack から呼び出し元の Enemy のHPを更新する引数型は？",
      choices: ["Enemy enemy", "const Enemy& enemy", "Enemy& enemy"],
      answer: 2,
      explanation: "Enemy& は呼び出し元オブジェクトの別名で、変更を反映できます。",
    },
    prompt: "Enemy、Weapon、battle 名前空間を定義します。Weapon::Sword のダメージは5、Weapon::Magic は12です。HPと武器コード（1はSword、2はMagic）を読み、battle::attack でHPを0未満にならないよう更新し、残りHPを表示してください。",
    solution: "#include <algorithm>\n#include <iostream>\n\nenum class Weapon { Sword, Magic };\nstruct Enemy { int hp; };\n\nnamespace battle {\nint damageFor(Weapon weapon) {\n    if (weapon == Weapon::Sword) return 5;\n    return 12;\n}\nvoid attack(Enemy& enemy, Weapon weapon) {\n    enemy.hp = std::max(0, enemy.hp - damageFor(weapon));\n}\n}\n\nint main() {\n    Enemy enemy{};\n    int weaponCode{};\n    std::cin >> enemy.hp >> weaponCode;\n    const Weapon weapon{weaponCode == 1 ? Weapon::Sword : Weapon::Magic};\n    battle::attack(enemy, weapon);\n    std::cout << enemy.hp << '\\n';\n    return 0;\n}",
    input: "30 2\n",
    tests: [
      { input: "30 2\n", output: "18" },
      { input: "4 1\n", output: "0" },
      { input: "20 1\n", output: "15" },
    ],
    hints: [
      "Weapon の列挙値と Enemy のHPメンバーを定義します。",
      "damageFor と attack を battle 名前空間に置きます。",
      "attack の引数は Enemy& とし、std::max でHPの下限を0にします。",
    ],
    debug: {
      code: "namespace battle {\nvoid attack(Enemy enemy, int damage) { enemy.hp -= damage; }\n}\nattack(enemy, 12);",
      fix: "namespace battle {\nvoid attack(Enemy& enemy, int damage) { enemy.hp = std::max(0, enemy.hp - damage); }\n}\nbattle::attack(enemy, 12);",
      explanation: "呼び出し元を更新するには Enemy& で受け取り、名前空間内の関数は battle::attack と呼びます。",
    },
  },
];
