import type { LessonSeed } from "../lessons";

export const week5LessonSeeds: LessonSeed[] = [
  {
    title: "最初の関数を定義して呼び出す",
    goal: "処理を名前付きの関数へまとめ、定義と呼び出しを区別する。",
    minutes: 35,
    explanation: "関数は、名前を付けた処理のまとまりです。戻り値がない処理には void を使います。関数本体を定義しただけでは実行されず、main などから名前と丸括弧を書いて呼び出す必要があります。",
    example: "#include <iostream>\n\nvoid printReady() {\n    std::cout << \"ready\\n\";\n}\n\nint main() {\n    printReady();\n}",
    exampleOutput: "ready",
    commonMistake: "関数を定義しただけで実行されたと思い、呼び出しを書き忘れる。",
    quiz: {
      question: "void show() { ... } と定義した関数を実行するには？",
      choices: ["show(); と呼び出す", "関数名をコメントに書く", "return 0; を追加するだけ"],
      answer: 0,
      explanation: "関数本体は呼び出されたときに実行されます。定義と呼び出しは別の操作です。",
    },
    prompt: "void printReady() を定義し、main から呼び出して ready と1行で表示してください。",
    solution: "#include <iostream>\n\nvoid printReady() {\n    std::cout << \"ready\\n\";\n}\n\nint main() {\n    printReady();\n    return 0;\n}",
    input: "",
    tests: [{ input: "", output: "ready" }],
    hints: [
      "戻り値を書かない関数の戻り値型は void です。",
      "関数本体を main より前に定義できます。",
      "main 内に printReady(); と書いて実行します。",
    ],
    debug: {
      code: "#include <iostream>\n\nvoid printReady() {\n    std::cout << \"ready\\n\";\n}\n\nint main() {\n    return 0;\n}",
      fix: "#include <iostream>\n\nvoid printReady() {\n    std::cout << \"ready\\n\";\n}\n\nint main() {\n    printReady();\n    return 0;\n}",
      explanation: "関数は定義しただけでは動きません。main から呼び出す文が必要です。",
    },
  },
  {
    title: "引数でデータを受け渡す",
    goal: "関数の引数を使い、入力値に応じた処理を再利用する。",
    minutes: 35,
    explanation: "引数は呼び出し側から関数へ渡す値です。仮引数は関数内で使う名前付きの変数で、値渡しでは引数の値が関数の仮引数へコピーされます。今回の printDamage は値を受け取って表示します。",
    example: "#include <iostream>\n\nvoid printDamage(int amount) {\n    std::cout << \"damage: \" << amount << '\\n';\n}\n\nint main() {\n    printDamage(18);\n}",
    exampleOutput: "damage: 18",
    commonMistake: "関数に必要な引数を渡さずに呼び出す、または定義側の型と異なる値を渡す。",
    quiz: {
      question: "void show(int value) を show(12); と呼ぶと、仮引数 value に入る値は？",
      choices: ["12", "0", "関数の行番号"],
      answer: 0,
      explanation: "呼び出し時に渡した整数12が、仮引数 value の初期値になります。",
    },
    prompt: "整数を読み取り、void printDamage(int amount) を使って damage: <値> と表示してください。",
    solution: "#include <iostream>\n\nvoid printDamage(int amount) {\n    std::cout << \"damage: \" << amount << '\\n';\n}\n\nint main() {\n    int amount{};\n    std::cin >> amount;\n    printDamage(amount);\n    return 0;\n}",
    input: "18\n",
    tests: [
      { input: "18\n", output: "damage: 18" },
      { input: "0\n", output: "damage: 0" },
      { input: "37\n", output: "damage: 37" },
    ],
    hints: [
      "printDamage の仮引数を int amount とします。",
      "main で int を読み取り、その変数を呼び出し時に渡します。",
      "出力では固定文字列と amount を << でつなぎます。",
    ],
    debug: {
      code: "void printDamage(int amount) {\n    std::cout << amount << '\\n';\n}\n\nint main() {\n    int amount{};\n    std::cin >> amount;\n    printDamage();\n}",
      fix: "printDamage(amount);",
      explanation: "printDamage は int の引数を1つ必要とします。読み取った amount を渡します。",
    },
  },
  {
    title: "戻り値で計算結果を返す",
    goal: "計算を行う関数から値を返し、呼び出し側で利用する。",
    minutes: 40,
    explanation: "戻り値型は関数が呼び出し側へ返す値の型です。int add(int left, int right) は整数を返し、return で計算結果を返します。void 関数と違い、返された値を変数へ保存したり、別の式へ組み込んだりできます。",
    example: "#include <iostream>\n\nint add(int left, int right) {\n    return left + right;\n}\n\nint main() {\n    std::cout << add(4, 7) << '\\n';\n}",
    exampleOutput: "11",
    commonMistake: "戻り値を計算したのに return せず、呼び出し側で結果が使えない。",
    quiz: {
      question: "int add(int a, int b) の return a + b; がすることは？",
      choices: ["合計を呼び出し側へ返す", "画面へ必ず表示する", "関数をもう一度呼び出す"],
      answer: 0,
      explanation: "return は値を呼び出し側へ返し、その関数の実行を終えます。",
    },
    prompt: "整数2つを読み、int add(int left, int right) で合計を計算して表示してください。",
    solution: "#include <iostream>\n\nint add(int left, int right) {\n    return left + right;\n}\n\nint main() {\n    int left{}, right{};\n    std::cin >> left >> right;\n    const int result = add(left, right);\n    std::cout << result << '\\n';\n    return 0;\n}",
    input: "4 7\n",
    tests: [
      { input: "4 7\n", output: "11" },
      { input: "-3 5\n", output: "2" },
      { input: "0 0\n", output: "0" },
    ],
    hints: [
      "add の戻り値型は int です。",
      "関数の中で left + right を計算します。",
      "main で add(left, right) の戻り値を表示します。",
    ],
    debug: {
      code: "int add(int left, int right) {\n    return left - right;\n}",
      fix: "return left + right;",
      explanation: "関数の形と戻り値型は正しいため、計算式の演算子を確認します。",
    },
  },
  {
    title: "bool を返す判定関数",
    goal: "条件判定を bool 関数へまとめ、呼び出し側の分岐に使う。",
    minutes: 40,
    explanation: "bool は true または false を表します。判定関数は条件を返すようにすると、名前から目的が読み取りやすくなります。表示やゲーム状態の変更は呼び出し側で行うと、判定と入出力の責務を分けられます。",
    example: "#include <iostream>\n\nbool isAlive(int hp) {\n    return hp > 0;\n}\n\nint main() {\n    std::cout << (isAlive(1) ? \"alive\\n\" : \"down\\n\");\n}",
    exampleOutput: "alive",
    commonMistake: "HP が負数のときも生存と判定するなど、条件の境界を考えない。",
    quiz: {
      question: "bool isAlive(int hp) { return hp > 0; } の戻り値は hp=0 のとき？",
      choices: ["true", "false", "0除算で未定義"],
      answer: 1,
      explanation: "0 > 0 は false なので、生存していない判定になります。",
    },
    prompt: "整数 HP を読み、bool isAlive(int hp) で判定してください。true なら alive、false なら down と表示します。",
    solution: "#include <iostream>\n\nbool isAlive(int hp) {\n    return hp > 0;\n}\n\nint main() {\n    int hp{};\n    std::cin >> hp;\n    if (isAlive(hp)) std::cout << \"alive\\n\";\n    else std::cout << \"down\\n\";\n    return 0;\n}",
    input: "1\n",
    tests: [
      { input: "1\n", output: "alive" },
      { input: "0\n", output: "down" },
      { input: "-5\n", output: "down" },
    ],
    hints: [
      "isAlive の戻り値型は bool です。",
      "HP が0より大きいかを比較します。",
      "main で戻り値を if の条件に使います。",
    ],
    debug: {
      code: "bool isAlive(int hp) {\n    return hp;\n}",
      fix: "return hp > 0;",
      explanation: "hp をそのまま bool に変換すると、負数も true になります。生存条件を明示します。",
    },
  },
  {
    title: "ローカル変数と関数のスコープ",
    goal: "ローカル変数の有効範囲を理解し、値を戻り値で受け渡す。",
    minutes: 40,
    explanation: "関数の中で宣言したローカル変数は、その関数のブロック内で使えます。別の関数から直接参照できません。関数間で計算結果を渡すときは、引数と戻り値を使うと依存関係が明確になります。",
    example: "#include <iostream>\n\nint addBonus(int base) {\n    const int bonus{10};\n    return base + bonus;\n}\n\nint main() {\n    std::cout << addBonus(35) << '\\n';\n}",
    exampleOutput: "45",
    commonMistake: "関数の中で作ったローカル変数を、関数の外から使おうとする。",
    quiz: {
      question: "関数内で宣言したローカル変数 bonus を main から直接使える？",
      choices: ["使える。名前は全ファイルで共有される", "使えない。スコープの外にある", "static を付けなくても必ず残る"],
      answer: 1,
      explanation: "ローカル変数の名前が有効なのは、その宣言を含むブロック内です。",
    },
    prompt: "int addBonus(int base) を作り、base に10を加えた値を返してください。整数を読み、戻り値を表示します。",
    solution: "#include <iostream>\n\nint addBonus(int base) {\n    const int bonus{10};\n    return base + bonus;\n}\n\nint main() {\n    int base{};\n    std::cin >> base;\n    std::cout << addBonus(base) << '\\n';\n    return 0;\n}",
    input: "35\n",
    tests: [
      { input: "35\n", output: "45" },
      { input: "0\n", output: "10" },
      { input: "90\n", output: "100" },
    ],
    hints: [
      "bonus は addBonus の中で宣言します。",
      "addBonus の戻り値型を int にします。",
      "base + bonus を return し、main で結果を出力します。",
    ],
    debug: {
      code: "int addBonus(int base) {\n    int bonus{10};\n}\n\nint main() {\n    return base + bonus;\n}",
      fix: "int addBonus(int base) {\n    int bonus{10};\n    return base + bonus;\n}",
      explanation: "base と bonus は addBonus 内の名前です。計算と return も同じ関数内で行います。",
    },
  },
  {
    title: "統合：関数でHPを更新する",
    goal: "引数、戻り値、判定関数を組み合わせて小さなゲーム処理を書く。",
    minutes: 50,
    explanation: "ゲーム処理を関数へ分けると、HPを計算する処理と生存判定を別々に確認できます。applyDamage は新しいHPを返し、isAlive はその値を判定します。関数が値を返す設計なら、呼び出し順とデータの流れを追いやすくなります。",
    example: "#include <iostream>\n\nint applyDamage(int hp, int damage) {\n    return hp - damage;\n}\n\nbool isAlive(int hp) {\n    return hp > 0;\n}",
    exampleOutput: "HPの値と状態は入力に応じて変わる",
    commonMistake: "値渡しした hp のコピーだけを変更し、呼び出し側の変数が更新されたと思う。",
    quiz: {
      question: "int applyDamage(int hp, int damage) が値渡しで hp を変更したとき、main の元の hp は？",
      choices: ["関数内の変更だけでは変わらない", "必ず0になる", "同じ名前なので自動で変わる"],
      answer: 0,
      explanation: "値渡しでは関数の仮引数はコピーです。新しい値を使うには戻り値を代入します。",
    },
    prompt: "HP とダメージを読み、applyDamage(hp, damage) で新しいHPを計算してください。HP: <値> と、生存なら alive、それ以外なら down を表示します。",
    solution: "#include <iostream>\n\nint applyDamage(int hp, int damage) {\n    return hp - damage;\n}\n\nbool isAlive(int hp) {\n    return hp > 0;\n}\n\nint main() {\n    int hp{}, damage{};\n    std::cin >> hp >> damage;\n    const int updatedHp = applyDamage(hp, damage);\n    std::cout << \"HP: \" << updatedHp << '\\n';\n    std::cout << (isAlive(updatedHp) ? \"alive\\n\" : \"down\\n\");\n    return 0;\n}",
    input: "50 13\n",
    tests: [
      { input: "50 13\n", output: "HP: 37\nalive" },
      { input: "5 7\n", output: "HP: -2\ndown" },
      { input: "10 0\n", output: "HP: 10\nalive" },
    ],
    hints: [
      "applyDamage は int を返し、HP からダメージを引きます。",
      "返された値を updatedHp などの変数へ保存します。",
      "isAlive(updatedHp) の結果を条件にして状態を出します。",
    ],
    debug: {
      code: "void applyDamage(int hp, int damage) {\n    hp -= damage;\n}\n\nint main() {\n    int updatedHp = applyDamage(50, 13);\n}",
      fix: "int applyDamage(int hp, int damage) {\n    return hp - damage;\n}",
      explanation: "計算結果を呼び出し側で使うので、void ではなく int を返す関数にします。",
    },
  },
  {
    title: "週末評価：上限付きスコア計算",
    goal: "関数の定義、引数、戻り値、分岐を使い、境界値を含む課題を解く。",
    minutes: 50,
    explanation: "週末の確認では資料を閉じ、引数から戻り値までのデータの流れを自力で組み立てます。base は0〜100、bonus は0〜20とします。合計が100を超えたら100に丸め、それ以外は合計を返します。",
    example: "#include <iostream>\n\nint finalScore(int base, int bonus) {\n    const int total = base + bonus;\n    if (total > 100) return 100;\n    return total;\n}",
    exampleOutput: "base と bonus の合計。ただし最大100",
    commonMistake: "合計が上限以下の経路で return を忘れたり、100ちょうども過剰に丸めたりする。",
    quiz: {
      question: "total が100ちょうどのとき、total > 100 は？",
      choices: ["true", "false", "実行時エラー"],
      answer: 1,
      explanation: "100は100より大きくありません。上限ちょうどの値はそのまま返します。",
    },
    prompt: "base と bonus を読み、int finalScore(int base, int bonus) を呼び出して結果を表示してください。合計が100を超えるときは100を返します。",
    solution: "#include <iostream>\n\nint finalScore(int base, int bonus) {\n    const int total = base + bonus;\n    if (total > 100) return 100;\n    return total;\n}\n\nint main() {\n    int base{}, bonus{};\n    std::cin >> base >> bonus;\n    std::cout << finalScore(base, bonus) << '\\n';\n    return 0;\n}",
    input: "60 20\n",
    tests: [
      { input: "60 20\n", output: "80" },
      { input: "92 15\n", output: "100" },
      { input: "0 0\n", output: "0" },
    ],
    hints: [
      "base + bonus を total に保存します。",
      "total が100を超える場合は先に100を返します。",
      "それ以外の経路でも total を return します。",
    ],
    debug: {
      code: "int finalScore(int base, int bonus) {\n    const int total = base + bonus;\n    if (total > 100) return 100;\n}",
      fix: "    return total;",
      explanation: "上限を超えない場合の戻り値がありません。すべての経路で int を返します。",
    },
  },
];
