import type { LessonSeed } from "../lessons";

export const week6LessonSeeds: LessonSeed[] = [
  {
    title: "std::array と添字",
    goal: "固定個数の値をまとめ、0から始まる添字で要素を読む。",
    minutes: 35,
    explanation: "std::array<int, 3> は int を3個まとめて保持する固定長コンテナです。先頭の添字は0なので、2番目の要素は values[1] で読みます。添字に要素数以上の値を使うと配列の範囲外へアクセスするため、要素数と添字の関係を確認します。",
    example: "#include <array>\n#include <iostream>\n\nint main() {\n    const std::array<int, 3> values{4, 7, 9};\n    std::cout << values[1] << '\\n';\n}",
    exampleOutput: "7",
    commonMistake: "2番目の要素を values[2] と書き、3番目を読んでしまう。",
    quiz: {
      question: "std::array<int, 3> values の2番目の要素を読む添字は？",
      choices: ["0", "1", "2"],
      answer: 1,
      explanation: "添字は0から始まるため、2番目は添字1です。",
    },
    prompt: "整数を3つ読み、std::array<int, 3> に保存してください。2番目の値を1行で表示します。",
    solution: "#include <array>\n#include <iostream>\n\nint main() {\n    std::array<int, 3> values{};\n    std::cin >> values[0] >> values[1] >> values[2];\n    std::cout << values[1] << '\\n';\n    return 0;\n}",
    input: "4 7 9\n",
    tests: [
      { input: "4 7 9\n", output: "7" },
      { input: "-2 0 15\n", output: "0" },
      { input: "100 50 25\n", output: "50" },
    ],
    hints: [
      "<array> をインクルードし、std::array<int, 3> を宣言します。",
      "入力は values[0]、values[1]、values[2] の順に読みます。",
      "2番目は values[1] です。",
    ],
    debug: {
      code: "std::array<int, 3> values{4, 7, 9};\nstd::cout << values[3];",
      fix: "std::cout << values[2];",
      explanation: "有効な添字は0、1、2です。values[3] は3要素の範囲外です。",
    },
  },
  {
    title: "ループで配列を処理する",
    goal: "添字と for 文を使い、配列の全要素を合計する。",
    minutes: 40,
    explanation: "同じ処理を複数の要素へ行うときは、for 文で添字を変えながら配列をたどれます。3要素なら添字は0、1、2です。ループ条件を i < 3 とすれば、最後に使う添字は2になります。",
    example: "#include <array>\n#include <iostream>\n\nint main() {\n    const std::array<int, 3> values{3, 5, 8};\n    int total{};\n    for (int i = 0; i < 3; ++i) {\n        total += values[i];\n    }\n    std::cout << total << '\\n';\n}",
    exampleOutput: "16",
    commonMistake: "条件を i <= 3 にして、存在しない4番目の要素を処理する。",
    quiz: {
      question: "3要素の添字を0から順に処理する条件は？",
      choices: ["i < 3", "i <= 3", "i > 3"],
      answer: 0,
      explanation: "i < 3 なら i は0、1、2のときに実行されます。",
    },
    prompt: "整数を3つ読み、for 文を使って合計を表示してください。",
    solution: "#include <array>\n#include <iostream>\n\nint main() {\n    std::array<int, 3> values{};\n    for (int i = 0; i < 3; ++i) {\n        std::cin >> values[i];\n    }\n    int total{};\n    for (int i = 0; i < 3; ++i) {\n        total += values[i];\n    }\n    std::cout << total << '\\n';\n    return 0;\n}",
    input: "3 5 8\n",
    tests: [
      { input: "3 5 8\n", output: "16" },
      { input: "0 0 0\n", output: "0" },
      { input: "-4 10 2\n", output: "8" },
    ],
    hints: [
      "std::array<int, 3> と int total{} を用意します。",
      "入力用と合計用に、それぞれ i < 3 のループを使います。",
      "合計用ループでは total += values[i]; とします。",
    ],
    debug: {
      code: "for (int i = 0; i <= 3; ++i) {\n    total += values[i];\n}",
      fix: "for (int i = 0; i < 3; ++i) {\n    total += values[i];\n}",
      explanation: "<= 3 では添字3まで処理します。3要素の有効な添字は0から2です。",
    },
  },
  {
    title: "std::string で文字列を扱う",
    goal: "標準ライブラリの文字列を読み取り、出力に組み込む。",
    minutes: 35,
    explanation: "std::string は長さが変わる文字列を扱う型です。<string> をインクルードし、std::cin >> name; と書くと空白までの1語を読み取れます。空白を含む行全体は次の授業で扱う std::getline を使います。",
    example: "#include <iostream>\n#include <string>\n\nint main() {\n    const std::string name{\"Ada\"};\n    std::cout << \"Hello, \" << name << '\\n';\n}",
    exampleOutput: "Hello, Ada",
    commonMistake: "std::string の宣言に必要な <string> をインクルードし忘れる。",
    quiz: {
      question: "std::cin >> name; が文字列を読むとき、基本的にどこまで読む？",
      choices: ["空白までの1語", "常にファイル全体", "整数だけ"],
      answer: 0,
      explanation: "operator>> は空白文字で区切られた次の1語を読み取ります。",
    },
    prompt: "英字の名前を1語読み、Hello, <名前> と1行で表示してください。",
    solution: "#include <iostream>\n#include <string>\n\nint main() {\n    std::string name;\n    std::cin >> name;\n    std::cout << \"Hello, \" << name << '\\n';\n    return 0;\n}",
    input: "Ada\n",
    tests: [
      { input: "Ada\n", output: "Hello, Ada" },
      { input: "Reito\n", output: "Hello, Reito" },
      { input: "Cplusplus\n", output: "Hello, Cplusplus" },
    ],
    hints: [
      "文字列型には std::string を使います。",
      "入力用の name を用意して std::cin >> name; とします。",
      "固定文字列と name を std::cout の << でつなぎます。",
    ],
    debug: {
      code: "#include <iostream>\nint main() {\n    std::string name;\n    std::cin >> name;\n}",
      fix: "#include <iostream>\n#include <string>\nint main() {\n    std::string name;\n    std::cin >> name;\n}",
      explanation: "std::string を宣言するには <string> をインクルードします。",
    },
  },
  {
    title: "getline で空白を含む行を読む",
    goal: "std::getline を使い、空白を含む文字列を1行分読み取る。",
    minutes: 40,
    explanation: "std::cin >> text; は空白で入力を区切ります。行全体を読みたい場合は std::getline(std::cin, text); を使います。getline は行末の改行を文字列に含めず、行の途中にある空白は保持します。",
    example: "#include <iostream>\n#include <string>\n\nint main() {\n    std::string title;\n    std::getline(std::cin, title);\n    std::cout << \"title: \" << title << '\\n';\n}",
    exampleOutput: "title: C++ Game",
    commonMistake: "空白を含む入力に std::cin >> を使い、最初の単語だけで読み取りが止まる。",
    quiz: {
      question: "入力行の空白も含めて読み取る関数は？",
      choices: ["std::getline", "std::cout", "std::size"],
      answer: 0,
      explanation: "std::getline は区切り文字までの1行を文字列に読み取ります。",
    },
    prompt: "1行の文章を読み、text: <入力した文章> と表示してください。途中の空白を残します。",
    solution: "#include <iostream>\n#include <string>\n\nint main() {\n    std::string text;\n    std::getline(std::cin, text);\n    std::cout << \"text: \" << text << '\\n';\n    return 0;\n}",
    input: "Hello C++\n",
    tests: [
      { input: "Hello C++\n", output: "text: Hello C++" },
      { input: "two words here\n", output: "text: two words here" },
      { input: "single\n", output: "text: single" },
    ],
    hints: [
      "入力行を保存する std::string text; を用意します。",
      "std::getline(std::cin, text); で1行を読みます。",
      "std::cout << \"text: \" << text; と表示します。",
    ],
    debug: {
      code: "std::string text;\nstd::cin >> text;\nstd::cout << text;",
      fix: "std::string text;\nstd::getline(std::cin, text);\nstd::cout << text;",
      explanation: ">> は空白で止まります。行全体が必要なら getline を使います。",
    },
  },
  {
    title: "ポインタで値を参照する",
    goal: "アドレスを保持するポインタと、* による間接参照を区別する。",
    minutes: 45,
    explanation: "ポインタはオブジェクトのアドレスを保持する変数です。&value は value のアドレスを取り、int* p は int を指すポインタを宣言します。*p はそのアドレスにある int の値を読み書きします。ポインタを使うときは、指す先のオブジェクトが存在していることを確認します。",
    example: "#include <iostream>\n\nint main() {\n    int hp{40};\n    int* hpAddress{&hp};\n    std::cout << *hpAddress << '\\n';\n}",
    exampleOutput: "40",
    commonMistake: "ポインタ変数に入っているアドレスと、そのアドレス先の値を混同する。",
    quiz: {
      question: "int* p = &value; の p が保持するものは？",
      choices: ["value のアドレス", "value の型名", "必ず0"],
      answer: 0,
      explanation: "&value は value のアドレスを取得し、ポインタ p に保存します。",
    },
    prompt: "整数を読み、int* ポインタを使ってその値を参照し、表示してください。",
    solution: "#include <iostream>\n\nint main() {\n    int value{};\n    std::cin >> value;\n    int* valueAddress{&value};\n    std::cout << *valueAddress << '\\n';\n    return 0;\n}",
    input: "42\n",
    tests: [
      { input: "42\n", output: "42" },
      { input: "0\n", output: "0" },
      { input: "-8\n", output: "-8" },
    ],
    hints: [
      "整数のローカル変数 value を先に宣言します。",
      "int* valueAddress{&value}; でそのアドレスを保持します。",
      "ポインタの指す値は *valueAddress で読み取れます。",
    ],
    debug: {
      code: "int value{42};\nint* address{&value};\nstd::cout << address;",
      fix: "std::cout << *address;",
      explanation: "address を出力するとアドレス値が表示されます。値を読むには間接参照の * を使います。",
    },
  },
  {
    title: "ポインタで配列をたどる",
    goal: "配列の先頭要素を指すポインタを進め、範囲内の要素を読む。",
    minutes: 45,
    explanation: "std::array の data() は先頭要素へのポインタを返します。ポインタを ++ すると次の要素へ進み、*current で現在の要素を読みます。配列の要素数だけ進めて止めます。配列末尾の1つ先を指す位置は作れますが、その位置を間接参照してはいけません。",
    example: "#include <array>\n#include <iostream>\n\nint main() {\n    const std::array<int, 3> values{2, 4, 6};\n    const int* current{values.data()};\n    for (int i = 0; i < 3; ++i) {\n        std::cout << *current << ' ';\n        ++current;\n    }\n}",
    exampleOutput: "2 4 6",
    commonMistake: "要素数を超えてポインタを進めて読み取り、配列の外を参照する。",
    quiz: {
      question: "const int* current が配列要素を指すとき、現在の要素を読む式は？",
      choices: ["current", "*current", "&*"],
      answer: 1,
      explanation: "*current はポインタが指している現在の要素を表します。",
    },
    prompt: "整数を3つ std::array に読み込み、data() から始まるポインタを使って先頭から順に表示してください。値の間は空白で区切ります。",
    solution: "#include <array>\n#include <iostream>\n\nint main() {\n    std::array<int, 3> values{};\n    for (int i = 0; i < 3; ++i) {\n        std::cin >> values[i];\n    }\n    int* current{values.data()};\n    for (int i = 0; i < 3; ++i) {\n        if (i > 0) std::cout << ' ';\n        std::cout << *current;\n        ++current;\n    }\n    std::cout << '\\n';\n    return 0;\n}",
    input: "4 7 9\n",
    tests: [
      { input: "4 7 9\n", output: "4 7 9" },
      { input: "0 -1 8\n", output: "0 -1 8" },
      { input: "12 12 12\n", output: "12 12 12" },
    ],
    hints: [
      "入力後に int* current{values.data()}; とします。",
      "3回のループで *current を出力し、current を ++ します。",
      "最後に余分な空白を付けないよう、i > 0 のときだけ区切りを表示します。",
    ],
    debug: {
      code: "int* current{values.data()};\nfor (int i = 0; i <= 3; ++i) {\n    std::cout << *current << ' ';\n    ++current;\n}",
      fix: "for (int i = 0; i < 3; ++i) {\n    std::cout << *current << ' ';\n    ++current;\n}",
      explanation: "3要素ならポインタを間接参照するのは3回です。4回目は配列外です。",
    },
  },
  {
    title: "統合：ポインタと要素数を渡す関数",
    goal: "配列の先頭ポインタと要素数を関数へ渡し、合計を返す。",
    minutes: 50,
    explanation: "配列を受け取る関数では、先頭要素のポインタと要素数を組にして渡せます。ポインタだけでは要素数が分からないため、count を別の引数にします。const int* は関数内から要素を書き換えないことを示します。count の範囲内だけを読み取ることが大切です。",
    example: "int sum(const int* values, int count) {\n    int total{};\n    for (int i = 0; i < count; ++i) {\n        total += values[i];\n    }\n    return total;\n}",
    exampleOutput: "3要素が 3, 5, 8 の場合は 16",
    commonMistake: "ポインタだけで要素数まで分かると思い込み、渡された範囲を超えて読み取る。",
    quiz: {
      question: "配列の先頭ポインタと一緒に要素数を渡す理由は？",
      choices: ["ポインタから要素数は自動では分からないため", "C++の関数は配列を読めないため", "const を使えなくするため"],
      answer: 0,
      explanation: "通常のポインタは指し先の要素数を保持しません。処理する範囲を別に渡します。",
    },
    prompt: "整数を3つ std::array に読み、sum(const int* values, int count) に先頭アドレスと要素数を渡してください。関数の戻り値を表示します。",
    solution: "#include <array>\n#include <iostream>\n\nint sum(const int* values, int count) {\n    int total{};\n    for (int i = 0; i < count; ++i) {\n        total += values[i];\n    }\n    return total;\n}\n\nint main() {\n    std::array<int, 3> values{};\n    for (int i = 0; i < 3; ++i) {\n        std::cin >> values[i];\n    }\n    std::cout << sum(values.data(), static_cast<int>(values.size())) << '\\n';\n    return 0;\n}",
    input: "3 5 8\n",
    tests: [
      { input: "3 5 8\n", output: "16" },
      { input: "-4 10 2\n", output: "8" },
      { input: "0 0 0\n", output: "0" },
    ],
    hints: [
      "sum の引数は const int* values と int count にします。",
      "関数内で count 回だけ values[i] を total に加算します。",
      "呼び出し時は values.data() と static_cast<int>(values.size()) を渡します。",
    ],
    debug: {
      code: "int sum(const int* values, int count) {\n    int total{};\n    for (int i = 0; i <= count; ++i) total += values[i];\n    return total;\n}",
      fix: "for (int i = 0; i < count; ++i) total += values[i];",
      explanation: "count 個の要素の有効な添字は0から count-1 です。<= count だと1つ範囲を超えます。",
    },
  },
];
